@startuml

' --- CLASES DE PERSONAJES ---
abstract class Personaje {
  + int vida
}
abstract class AnimalAmigo

class DonkeyKong {
  + Lanzar(Barril objeto)
  + Golpear(Martillo herramienta)
}
class DiddyKong
class CrankyKong

' --- OBJETOS E ITEMS ---
class Barril {
  + float peso
  + float potenciaLanzamiento
}
class BarrilTNT
class BarrilAcero
class BarrilCañon
class Martillo
class BastonCranky

' --- ANIMALES ---
class Rambi
class Enguarde
class Expresso
class Winky

' --- OTROS ELEMENTOS ---
class MonedaDK
class Nivel
class Mundo
class Partida

' --- RELACIONES "ES" (Herencia) ---
DonkeyKong --|> Personaje
DiddyKong --|> Personaje
CrankyKong --|> Personaje

Rambi --|> AnimalAmigo
Enguarde --|> AnimalAmigo
Expresso --|> AnimalAmigo
Winky --|> AnimalAmigo

BarrilTNT --|> Barril
BarrilAcero --|> Barril

' --- RELACIONES "TIENE" (Composición) ---
CrankyKong "1" *-- "1" BastonCranky
Nivel "1" *-- "1" K
' (Otras letras K-O-N-G irían aquí)

' --- RELACIONES "USA" (Agregación + Acción Objeto Entrada) ---
' Aquí aplicamos lo del pizarrón:
' Acción: Lanzar (termina en -ar) 
' Objeto de entrada: Barril
DonkeyKong o-- Barril : "Lanzar(barril)"
DonkeyKong o-- Martillo : "Golpear(martillo)"

Personaje o-- MonedaDK : "Recolectar(moneda)"
AnimalAmigo o-- Cofredeltesoro : "Abrir(cofre)"

@enduml
